name: "Insert the latest monster prices"
on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *' # Run every 10 minutes


jobs:
  insert-the-latest-monster-prices:
    name: "Insert the latest monster prices"
    runs-on: ubuntu-latest

    steps:
      - name: "Insert the latest monster prices"
        run: curl "https://monsterindeks.fly.dev/insert-latest-monster-price"
