name: "Insert the latest monster prices"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * *' # Run every day at 11:00 UTC

jobs:
  insert-the-latest-monster-prices:
    name: "Insert the latest monster prices"
    runs-on: ubuntu-24.04-arm

    steps:
      - name: "Insert the latest monster prices"
        run: curl "https://monsterindeks.fly.dev/insert-latest-monster-price"
